DEBUG = True

WINDOW_WITDH = 700
WINDOW_HEIGHT = 600

KOMIKU = {
    "CHAPTER_LIST_FOLDER"   : "0_CHAPTER_LIST_KOMIKU",
    "IMAGE_FOLDER"          : "0_IMAGE_KOMIKU",
}

SHINIGAMI = {
    "CHAPTER_LIST_FOLDER"   : "0_CHAPTER_LIST_SHINIGAMI",
    "IMAGE_FOLDER"          : "0_IMAGE_SHINIGAMI",
}

SOFTKOMIK = {
    "CHAPTER_LIST_FOLDER"   : "0_CHAPTER_LIST_SOFTKOMIK",
    "IMAGE_FOLDER"          : "0_IMAGE_SOFTKOMIK",
}

KUNMANGA = {
    "CHAPTER_LIST_FOLDER"   : "0_CHAPTER_LIST_KUNMANGA",
    "IMAGE_FOLDER"          : "0_IMAGE_KUNMANGA",
}

KOMIKINDO = {
    "CHAPTER_LIST_FOLDER"   : "0_CHAPTER_LIST_KOMIKINDO",
    "IMAGE_FOLDER"          : "0_IMAGE_KOMIKINDO",
}