DEBUG = True

WINDOW_WITDH = 700
WINDOW_HEIGHT = 600

KOMIKU = {
    "CHAPTER_LIST_FOLDER"   : "0_CHAPTER_LIST_KOMIKU",
    "IMAGE_FOLDER"          : "0_IMAGE_KOMIKU",
}

SHINIGAMI = {
    "CHAPTER_LIST_FOLDER"   : "0_CHAPTER_LIST_SHINIGAMI",
    "IMAGE_FOLDER"          : "0_IMAGE_SHINIGAMI",
}